###
GET  http://localhost:3000/notes/


###
POST http://localhost:3000/notes/
Content-Type: application/json

{
    "title":"new note 3",
    "content":"add new note."
}

###
DELETE http://localhost:3000/notes/661bce32c3ab93c81288e017

###
PATCH  http://localhost:3000/notes/661be3fbc10f48b5d3f4e405
Content-Type: application/json

{
    "title":"updated the note"
}
###
GET http://localhost:3000/notes/search?query=new note 2

