###
GET  http://localhost:3000/notes/


###
POST http://localhost:3000/notes/
Content-Type: application/json

{
    "title":"new note 4",
    "content":"add new note."
}

###
DELETE http://localhost:3000/notes/661bcf2c25c537881719326b

###
PATCH  http://localhost:3000/notes/661bd067bfcd439d1f9bf6e9
Content-Type: application/json

{
    "title": "update the task"
}
###
GET http://localhost:3000/notes/search?query=new note 2

